name: CI tests

on:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        py_version: [ '3.7', '3.8', '3.9' ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.py_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py_version }}
          architecture: x64

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Test with pytest
        run: |
          pip install pytest
          pytest
